insert into Patient (id, name, phone, address, city, state) values (1, 'Tish Warstall', '(805) 2235370', '7047 Clyde Gallagher Circle', 'San Mateo', 'CA');
insert into Patient (id, name, phone, address, city, state) values (2, 'Tyrus Gavin', '(352) 5819840', '67 Arkansas Crossing', 'Gainesville', 'FL');
insert into Patient (id, name, phone, address, city, state) values (3, 'Rooney Atcheson', '(303) 8181180', '27 Park Meadow Court', 'Boulder', 'CO');
insert into Patient (id, name, phone, address, city, state) values (4, 'Kordula Ritson', '(936) 8544328', '06229 Roxbury Place', 'Conroe', 'TX');
insert into Patient (id, name, phone, address, city, state) values (5, 'Melba Sim', '(201) 6657592', '92 Rutledge Road', 'Jersey City', 'NJ');
insert into Patient (id, name, phone, address, city, state) values (6, 'Kenton Waggitt', '(702) 5070274', '775 Lien Drive', 'Las Vegas', 'NV');
insert into Patient (id, name, phone, address, city, state) values (7, 'Bjorn Clamo', '(352) 4547428', '32 Anzinger Terrace', 'Ocala', 'FL');
insert into Patient (id, name, phone, address, city, state) values (8, 'Jarvis Silbersak', '(662) 4179229', '04162 Helena Crossing', 'Columbus', 'MS');
insert into Patient (id, name, phone, address, city, state) values (9, 'Clayborne Shapira', '(904) 3368688', '2166 Claremont Center', 'Saint Augustine', 'FL');
insert into Patient (id, name, phone, address, city, state) values (10, 'Inger Robbings', '(513) 8163870', '3 Everett Center', 'Cincinnati', 'OH');
insert into Patient (id, name, phone, address, city, state) values (11, 'Rhianna Verty', '(210) 3833234', '75 Huxley Road', 'San Antonio', 'TX');
insert into Patient (id, name, phone, address, city, state) values (12, 'Lin Boldra', '(217) 4584111', '38 Gulseth Drive', 'Springfield', 'IL');
insert into Patient (id, name, phone, address, city, state) values (13, 'Joletta Probey', '(713) 2358421', '97 Sullivan Street', 'Houston', 'TX');
insert into Patient (id, name, phone, address, city, state) values (14, 'Eugenie Foskin', '(901) 5372186', '01 Northport Circle', 'Memphis', 'TN');
insert into Patient (id, name, phone, address, city, state) values (15, 'Bucky Curling', '(901) 7390292', '818 Veith Hill', 'Memphis', 'TN');
insert into Patient (id, name, phone, address, city, state) values (16, 'Stacee Farguhar', '(650) 7420960', '46432 Main Point', 'Santa Clara', 'CA');
insert into Patient (id, name, phone, address, city, state) values (17, 'Lesly Gegg', '(814) 1878028', '0 Magdeline Court', 'Erie', 'PA');
insert into Patient (id, name, phone, address, city, state) values (18, 'Blanch Houseman', '(202) 7099310', '9734 Golf Course Park', 'Washington', 'DC');
insert into Patient (id, name, phone, address, city, state) values (19, 'Gypsy Blas', '(909) 4517079', '6 Doe Crossing Alley', 'San Bernardino', 'CA');
insert into Patient (id, name, phone, address, city, state) values (20, 'Caralie Usher', '(570) 6589612', '8149 Mcguire Lane', 'Scranton', 'PA');
insert into Patient (id, name, phone, address, city, state) values (21, 'Benny Rubartelli', '(612) 7964058', '657 Twin Pines Park', 'Saint Paul', 'MN');
insert into Patient (id, name, phone, address, city, state) values (22, 'Paola Lackinton', '(254) 4975834', '03 Jackson Point', 'Killeen', 'TX');
insert into Patient (id, name, phone, address, city, state) values (23, 'Jacklin Fredy', '(360) 6270778', '67012 Stang Point', 'Vancouver', 'WA');
insert into Patient (id, name, phone, address, city, state) values (24, 'Horacio Bakhrushin', '(505) 3492807', '14182 Nevada Terrace', 'Albuquerque', 'NM');
insert into Patient (id, name, phone, address, city, state) values (25, 'Ola Hing', '(757) 7173117', '2 Elgar Center', 'Virginia Beach', 'VA');
insert into Patient (id, name, phone, address, city, state) values (26, 'Alric Gothard', '(215) 8456396', '7739 Longview Point', 'Philadelphia', 'PA');
insert into Patient (id, name, phone, address, city, state) values (27, 'Charmaine Maiklem', '(949) 3669432', '120 Miller Hill', 'Irvine', 'CA');
insert into Patient (id, name, phone, address, city, state) values (28, 'Mallissa Clementson', '(614) 1448411', '367 Brentwood Alley', 'Columbus', 'OH');
insert into Patient (id, name, phone, address, city, state) values (29, 'Nilson Webland', '(717) 7590888', '8510 Utah Park', 'Lancaster', 'PA');
insert into Patient (id, name, phone, address, city, state) values (30, 'Marthe Stimpson', '(904) 8962004', '97726 Sullivan Center', 'Jacksonville', 'FL');
insert into Patient (id, name, phone, address, city, state) values (31, 'Sheelah Mannooch', '(808) 9110533', '4617 Carey Street', 'Honolulu', 'HI');
insert into Patient (id, name, phone, address, city, state) values (32, 'Gunar O''Cahey', '(816) 8434503', '8 Ridgeview Street', 'Kansas City', 'MO');
insert into Patient (id, name, phone, address, city, state) values (33, 'Xerxes Wrist', '(678) 1193454', '76932 Loftsgordon Way', 'Lawrenceville', 'GA');
insert into Patient (id, name, phone, address, city, state) values (34, 'Cos Schreurs', '(812) 3921910', '969 Bultman Place', 'Jeffersonville', 'IN');
insert into Patient (id, name, phone, address, city, state) values (35, 'Marilin Cowthart', '(862) 8208094', '29 High Crossing Parkway', 'Paterson', 'NJ');
insert into Patient (id, name, phone, address, city, state) values (36, 'Robina Fatkin', '(805) 8458997', '5 Merry Terrace', 'Oxnard', 'CA');
insert into Patient (id, name, phone, address, city, state) values (37, 'Weidar Debell', '(253) 2750110', '655 Memorial Circle', 'Tacoma', 'WA');
insert into Patient (id, name, phone, address, city, state) values (38, 'Rockwell Atchly', '(317) 7028690', '0772 Vernon Crossing', 'Indianapolis', 'IN');
insert into Patient (id, name, phone, address, city, state) values (39, 'Northrop Gilgryst', '(205) 3750002', '90978 Spaight Pass', 'Birmingham', 'AL');
insert into Patient (id, name, phone, address, city, state) values (40, 'Elora Bobasch', '(817) 2797212', '527 Manley Street', 'Fort Worth', 'TX');
insert into Patient (id, name, phone, address, city, state) values (41, 'Tate Geffcock', '(704) 7566385', '12 Blaine Center', 'Charlotte', 'NC');
insert into Patient (id, name, phone, address, city, state) values (42, 'Powell Tampin', '(309) 7678428', '19 Debs Plaza', 'Peoria', 'IL');
insert into Patient (id, name, phone, address, city, state) values (43, 'Egor Anwell', '(817) 8280775', '23 Mesta Terrace', 'Fort Worth', 'TX');
insert into Patient (id, name, phone, address, city, state) values (44, 'Christa Somerscales', '(864) 4092375', '846 Shopko Plaza', 'Greenville', 'SC');
insert into Patient (id, name, phone, address, city, state) values (45, 'Guido Scurlock', '(916) 1397021', '15 Rutledge Terrace', 'Sacramento', 'CA');
insert into Patient (id, name, phone, address, city, state) values (46, 'Thekla Morewood', '(214) 5413998', '36497 Springview Circle', 'Dallas', 'TX');
insert into Patient (id, name, phone, address, city, state) values (47, 'Beale Citrine', '(623) 2185024', '6 Calypso Place', 'Phoenix', 'AZ');
insert into Patient (id, name, phone, address, city, state) values (48, 'Laurent Stuck', '(318) 5130601', '299 Northridge Plaza', 'Monroe', 'LA');
insert into Patient (id, name, phone, address, city, state) values (49, 'Georgianne Goult', '(907) 8126279', '857 Graedel Plaza', 'Anchorage', 'AK');
insert into Patient (id, name, phone, address, city, state) values (50, 'Egor Meatyard', '(757) 1776664', '67340 Arizona Pass', 'Hampton', 'VA');
insert into Patient (id, name, phone, address, city, state) values (51, 'Tamma O''Lagen', '(716) 9142619', '6243 Cascade Place', 'Buffalo', 'NY');
insert into Patient (id, name, phone, address, city, state) values (52, 'Vicky Chesworth', '(214) 6422261', '87315 Messerschmidt Circle', 'Garland', 'TX');
insert into Patient (id, name, phone, address, city, state) values (53, 'Janine Maysor', '(719) 1374070', '5873 Ridgeway Pass', 'Pueblo', 'CO');
insert into Patient (id, name, phone, address, city, state) values (54, 'Renie Como', '(240) 1853769', '90 Norway Maple Avenue', 'Silver Spring', 'MD');
insert into Patient (id, name, phone, address, city, state) values (55, 'Bevin Jacobsen', '(952) 8504692', '265 Arizona Circle', 'Young America', 'MN');
insert into Patient (id, name, phone, address, city, state) values (56, 'Michele Broadfield', '(605) 2848270', '186 Sycamore Terrace', 'Sioux Falls', 'SD');
insert into Patient (id, name, phone, address, city, state) values (57, 'Rem Pettecrew', '(808) 6332807', '738 Cardinal Terrace', 'Honolulu', 'HI');
insert into Patient (id, name, phone, address, city, state) values (58, 'Dot Erdely', '(202) 6824355', '067 Stoughton Point', 'Washington', 'DC');
insert into Patient (id, name, phone, address, city, state) values (59, 'Fae Stanlake', '(402) 5361539', '64 Fremont Terrace', 'Omaha', 'NE');
insert into Patient (id, name, phone, address, city, state) values (60, 'Kathryn Brimm', '(434) 7351909', '8712 Carioca Trail', 'Manassas', 'VA');
insert into Patient (id, name, phone, address, city, state) values (61, 'Benn Filochov', '(510) 2942979', '8 Northridge Trail', 'Berkeley', 'CA');
insert into Patient (id, name, phone, address, city, state) values (62, 'Beryle MacCague', '(215) 6384578', '89796 Kennedy Avenue', 'Philadelphia', 'PA');
insert into Patient (id, name, phone, address, city, state) values (63, 'Myrwyn Rudyard', '(704) 3073260', '00 Barnett Parkway', 'Charlotte', 'NC');
insert into Patient (id, name, phone, address, city, state) values (64, 'Daloris McNeilly', '(859) 6397671', '5 Erie Road', 'Lexington', 'KY');
insert into Patient (id, name, phone, address, city, state) values (65, 'Eudora Gudgin', '(513) 3188182', '79 Arrowood Drive', 'Cincinnati', 'OH');
insert into Patient (id, name, phone, address, city, state) values (66, 'Dagny Drew-Clifton', '(860) 9085295', '3 Declaration Center', 'Hartford', 'CT');
insert into Patient (id, name, phone, address, city, state) values (67, 'Rosalinda Poxson', '(757) 2957276', '84400 Oak Valley Park', 'Norfolk', 'VA');
insert into Patient (id, name, phone, address, city, state) values (68, 'Lorene Tyne', '(815) 7495905', '80 Jackson Crossing', 'Joliet', 'IL');
insert into Patient (id, name, phone, address, city, state) values (69, 'Marietta Bunclark', '(770) 3824878', '539 Scofield Terrace', 'Duluth', 'GA');
insert into Patient (id, name, phone, address, city, state) values (70, 'Micky Cane', '(907) 4082974', '1 Jana Drive', 'Fairbanks', 'AK');
insert into Patient (id, name, phone, address, city, state) values (71, 'Genni Carah', '(256) 6583912', '090 Bunting Lane', 'Huntsville', 'AL');
insert into Patient (id, name, phone, address, city, state) values (72, 'Marge Bente', '(251) 8367128', '33 Hoffman Point', 'Mobile', 'AL');
insert into Patient (id, name, phone, address, city, state) values (73, 'Bel Hinnerk', '(832) 7689527', '297 Reinke Center', 'Houston', 'TX');
insert into Patient (id, name, phone, address, city, state) values (74, 'Pearla Wagge', '(713) 9746717', '36 Badeau Park', 'Houston', 'TX');
insert into Patient (id, name, phone, address, city, state) values (75, 'Kordula Trengrouse', '(727) 5758579', '62 Springview Junction', 'Largo', 'FL');
insert into Patient (id, name, phone, address, city, state) values (76, 'Ross Steele', '(952) 7630748', '65 Corscot Trail', 'Young America', 'MN');
insert into Patient (id, name, phone, address, city, state) values (77, 'Mirabella Lackham', '(214) 8912669', '62 Harbort Junction', 'Dallas', 'TX');
insert into Patient (id, name, phone, address, city, state) values (78, 'Glenna Liddiatt', '(915) 2236022', '67 Cambridge Avenue', 'El Paso', 'TX');
insert into Patient (id, name, phone, address, city, state) values (79, 'Birk Cowan', '(805) 6641132', '09 Montana Point', 'Simi Valley', 'CA');
insert into Patient (id, name, phone, address, city, state) values (80, 'Ferguson Matura', '(719) 3248701', '58 Scofield Hill', 'Colorado Springs', 'CO');
insert into Patient (id, name, phone, address, city, state) values (81, 'Brad Flucks', '(602) 1764051', '19 Rockefeller Point', 'Glendale', 'AZ');
insert into Patient (id, name, phone, address, city, state) values (82, 'Trey Earland', '(607) 8837893', '137 Montana Park', 'Elmira', 'NY');
insert into Patient (id, name, phone, address, city, state) values (83, 'Kirby Hebbs', '(214) 3800837', '9 Lindbergh Center', 'Dallas', 'TX');
insert into Patient (id, name, phone, address, city, state) values (84, 'Chad Antoniades', '(402) 1164524', '690 Artisan Center', 'Omaha', 'NE');
insert into Patient (id, name, phone, address, city, state) values (85, 'Sloane Baggelley', '(310) 8770952', '49286 Mayfield Street', 'San Francisco', 'CA');
insert into Patient (id, name, phone, address, city, state) values (86, 'Georgette Whifen', '(619) 9143492', '885 Pennsylvania Trail', 'San Diego', 'CA');
insert into Patient (id, name, phone, address, city, state) values (87, 'Nollie Grigs', '(212) 9059175', '021 Sycamore Court', 'New York City', 'NY');
insert into Patient (id, name, phone, address, city, state) values (88, 'Liv Agar', '(325) 7828941', '65419 Manley Terrace', 'San Angelo', 'TX');
insert into Patient (id, name, phone, address, city, state) values (89, 'Batsheva Keach', '(210) 5941721', '14 Killdeer Plaza', 'San Antonio', 'TX');
insert into Patient (id, name, phone, address, city, state) values (90, 'Obediah Fryd', '(239) 3681726', '10 Autumn Leaf Center', 'Naples', 'FL');
insert into Patient (id, name, phone, address, city, state) values (91, 'Tucker McGuire', '(404) 5437586', '4685 Cardinal Street', 'Atlanta', 'GA');
insert into Patient (id, name, phone, address, city, state) values (92, 'Mannie Sutor', '(405) 4031904', '88559 Mariners Cove Crossing', 'Oklahoma City', 'OK');
insert into Patient (id, name, phone, address, city, state) values (93, 'Codi Habershon', '(626) 8084541', '5 Anniversary Terrace', 'Los Angeles', 'CA');
insert into Patient (id, name, phone, address, city, state) values (94, 'Gilbert Houtbie', '(480) 1482948', '575 Amoth Place', 'Phoenix', 'AZ');
insert into Patient (id, name, phone, address, city, state) values (95, 'Milzie Chape', '(650) 9561680', '82567 Toban Parkway', 'Sunnyvale', 'CA');
insert into Patient (id, name, phone, address, city, state) values (96, 'Vanna Coverly', '(412) 6347314', '6454 Homewood Way', 'Mc Keesport', 'PA');
insert into Patient (id, name, phone, address, city, state) values (97, 'Karine Sapsforde', '(318) 7035602', '892 Atwood Pass', 'Shreveport', 'LA');
insert into Patient (id, name, phone, address, city, state) values (98, 'Kale McGourty', '(718) 5119896', '46 Pearson Plaza', 'Bronx', 'NY');
insert into Patient (id, name, phone, address, city, state) values (99, 'Leontine Dungey', '(319) 6154070', '64 Nancy Lane', 'Cedar Rapids', 'IA');
insert into Patient (id, name, phone, address, city, state) values (100, 'Blondelle Dradey', '(205) 3527010', '98900 Holmberg Road', 'Birmingham', 'AL');
